// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTiku = "tiku"

// Tiku mapped from table <tiku>
type Tiku struct {
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Question string `gorm:"column:question" json:"question"`
	Type     int32  `gorm:"column:type" json:"type"`
	Options  string `gorm:"column:options" json:"options"`
	Answer   string `gorm:"column:answer" json:"answer"`
	Plat     int32  `gorm:"column:plat" json:"plat"`
}

// TableName Tiku's table name
func (*Tiku) TableName() string {
	return TableNameTiku
}
