limit:
  enable: false # 是否开启
  duration: 3  # 时间窗口为3秒
  requests: 1  # 允许用户在3秒内通过1个请求
mysql: ""
database:
  path: "" # SQLite数据库文件路径，留空默认为 tiku.db（向后兼容），Docker部署建议设置为 data/tiku.db
api:
  - name: '样例接口 json 请求'
    enable: false
    url: http://lyck6.cn/scriptService/api/autoFreeAnswer
    method: POST
    headers:
      - key: Content-Type
        value: application/json
    body: '{"question":"${question}"}'
    answer: 'result.answers.0.0'

  - name: '样例接口 表单请求'
    enable: false
    url: https://cx.icodef.com/wyn-nb?v=4
    method: POST
    headers:
      - key: Content-Type
        value: application/x-www-form-urlencoded
    body: 'question=${question}'
    answer: 'data'
elasticsearch:
  url: http://127.0.0.1:9200
recordEmptyAnswer: false # 是否记录空答案（开启之后即便没有答案也会记录在数据库方便后期手动整理题库）
